version: "3.9"

services:
  redis:
    image: redis:7.4-alpine
    command: ["redis-server", "--appendonly", "yes"]
    container_name: challenge-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: challenge-dev:latest
    container_name: challenge-app
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=prod

      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379

      - JSONPLACEHOLDER_BASE_URL=https://jsonplaceholder.typicode.com
      - JSONPLACEHOLDER_CONNECT_TIMEOUT_MS=2000
      - JSONPLACEHOLDER_READ_TIMEOUT_MS=3000

      - SERVER_PORT=8080
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  redisdata:
